//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LodgeAround.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entity.Data;
    using Repository.Pattern.Ef6;
    
    public partial class LodgearoundEntities : DataContext
    {
        public LodgearoundEntities()
            : base("name=LodgearoundEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserInfos> UserInfos { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
