//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LodgeAround.Entity.Data
{
    using System;
    using System.Collections.Generic;
    using Repository.Pattern.Ef6;
    public partial class Logins : Entity
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Ip { get; set; }
        public System.DateTime LoginTime { get; set; }
        public int DeviceType { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
