//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LodgeAround.Entity.Data
{
    using System;
    using System.Collections.Generic;
    using Repository.Pattern.Ef6;
    public partial class Users : Entity
    {
        public Users()
        {
            this.Logins = new HashSet<Logins>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int Active { get; set; }
        public Nullable<int> UserInfosID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] rv { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual UserInfos UserInfos { get; set; }
        public virtual ICollection<Logins> Logins { get; set; }
    }
}
